### ISSUE TITLE
Read sensor inputs, update screen and MQTT broker

### ISSUE THREAD

**Issue by sperretta** [Matthewar/Embedded-Systems#4]
Submitting a form should display the current luminosity of the sensor.

DoD: A web page which displays the sensor output when submitted.

**Comment by Matthewar** [comment]
Should we change the issue, since the web issue is now irrelevant, to something along the lines of "Read sensors, update screen and broker" IE change this issue to be making the top level module that connects the inputs/outputs?

**Comment by sperretta** [comment]
Yes, that would make more sense. Thanks!

**Comment by Matthewar** [comment]
To use my I2C libraries (Light sensor and - currently unmade - colour sensor) you need to pass the I2C class so they can run on the same pins.

I recommend a method along the lines of:
```{python}
def I2CFunction(self,scl_pin=5,sda_pin=4):
    #Set I2C pins
    SCL_PIN = Pin(scl_pin)
    SDA_PIN = Pin(sda_pin)
    #Initialise I2C for bus
    self.i2c = I2C(-1,SCL_PIN,SDA_PIN)
    #Pass I2C to sensor(s)
    self.lightSensor = SensorLib(self.i2c,<Addr>)
```

**Comment by sperretta** [comment]
Good work Matthew, very helpful code snippet!

**Comment by Matthewar** [comment]
Code for callback function
```{python}
import json
def callback(self,topic,data):
    data_dict = json.loads(data)
    if topic == "esys\\time":
        jsonTimeString = data_dict['time']
        timeString = self.convTime(jsonTimeString)
        self.UpdateScreen(timeString)
    elif topic == "esys/tbd/command":
        self.alarmHour = data_dict['hour']
        self.alarmMin = data_dict['min']
```
