### ISSUE TITLE
Control LED output.

### ISSUE THREAD

**Issue by sperretta** [Matthewar/Embedded-Systems#5]
Ability to control the brightness of an LED (PWM).

DoD: Function to control brightness of LED.

**Comment by Rioplats** [comment]
Sorry for not updating regularly. Current code does not incorporate RGBLED elements, so I will need to look into this asap. Should I upload the code anyway?
Code takes in current light level, variable for alarm trigger, and a dummy variable for the sun which should in the long run prevent positive feedback.

Note: There should probably be fewer level transitions for the RGBLED, as currently it updates every loop cycle.
